version: '2'

services:
  nginx:
    ports:
      - "${HTTP_PORT}:80"
    build:
      context: ./containers/nginx
      dockerfile: ./Dockerfile
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
        PROJECT_PREFIX: "$PROJECT_PREFIX"
        DOCUMENT_ROOT: "$DOCUMENT_ROOT"
    container_name: ${PROJECT_PREFIX}_webserver
    depends_on:
      - mysql
    volumes:
      - ./../:/var/www/html
      - ./logs/nginx:/var/log/nginx
    links:
      - php
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
      - PROJECT_PREFIX=${PROJECT_PREFIX}
    networks:
      default:
        aliases:
          - site.root

  php:
    build:
      context: ./containers/php
      dockerfile: ./Dockerfile
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
        APP_ENV: "$APP_ENV"
    container_name: ${PROJECT_PREFIX}_php
    volumes:
      - ./../:/var/www/html
      - ./logs/php:/var/log/php
      - ./data/sessions:/var/www/sessions
    links:
      - mysql
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      PROJECT_PREFIX: "$PROJECT_PREFIX"
      DB_CONNECTION: "mysql"
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB_DATABASE: "dev"
      DB_USERNAME: "dev"
      DB_PASSWORD: "dev"



  mysql:
    build:
        context: ./containers/mysql
        dockerfile: ./Dockerfile
        args:
            USER_ID: "$USER_ID"
            GROUP_ID: "$GROUP_ID"
    container_name: ${PROJECT_PREFIX}_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./data/mysql:/var/lib/mysql

